# Generated by Django 5.1.7 on 2025-03-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('Location', models.TextField(max_length=100)),
                ('Category', models.CharField(max_length=20)),
            ],
        ),
    ]
