# Generated by Django 5.2 on 2025-04-26 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professorResponsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.professor'),
        ),
        migrations.RemoveField(
            model_name='professor',
            name='disciplinaAtribuida',
        ),
        migrations.AlterField(
            model_name='reservaambiente',
            name='dataInicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservaambiente',
            name='dataTermino',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservaambiente',
            name='disciplinaAssociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
        migrations.AlterField(
            model_name='reservaambiente',
            name='professorResponsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.professor'),
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplinaAtribuida',
            field=models.ManyToManyField(blank=True, to='app.disciplina'),
        ),
    ]
