# Generated by Django 5.2.1 on 2025-05-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('ni', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100, unique=True)),
                ('mac_address', models.CharField(max_length=100, unique=True)),
                ('unidade_med', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('latitude', models.FloatField(max_length=100)),
                ('longitude', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='api_smart.ambientes')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='api_smart.sensor')),
            ],
        ),
    ]
