# Generated by Django 5.2.1 on 2025-05-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_smart', '0002_sensor_status_alter_sensor_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.CharField(blank=True, choices=[('contador', 'Contador'), ('luminosidade', 'Luminosidade'), ('temperatura', 'Temperatura'), ('umidade', 'Umidade')], max_length=20, null=True),
        ),
    ]
