# Generated by Django 5.2.1 on 2025-05-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_smart', '0003_sensor_tipo_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.CharField(choices=[('contador', 'Contador'), ('luminosidade', 'Luminosidade'), ('temperatura', 'Temperatura'), ('umidade', 'Umidade')], default='temperatura', max_length=20),
        ),
    ]
