# Generated by Django 5.2.1 on 2025-05-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_smart', '0004_alter_historico_observacoes_alter_sensor_tipo_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(default='default_sensor_id', max_length=100, unique=True),
        ),
    ]
