# Generated by Django 5.2.1 on 2025-05-20 00:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_smart', '0005_alter_sensor_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
