# Generated by Django 5.1.7 on 2025-03-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userabs',
            old_name='cargo',
            new_name='animais',
        ),
        migrations.AddField(
            model_name='userabs',
            name='bio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userabs',
            name='endereco',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userabs',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userabs',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
