# Generated by Django 5.2 on 2025-04-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('cargaHoraria', models.IntegerField()),
                ('descricao', models.CharField(max_length=50)),
                ('professorResponsavel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=9)),
                ('Nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.PositiveIntegerField(blank=True, null=True)),
                ('dataNascimento', models.DateField()),
                ('dataContratacao', models.DateField()),
                ('disciplinaAtribuida', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservaAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.IntegerField()),
                ('dataTermino', models.IntegerField()),
                ('periodo', models.CharField(max_length=50)),
                ('salaReservada', models.CharField(max_length=50)),
                ('professorResponsavel', models.CharField(max_length=50)),
                ('disciplinaAssociada', models.CharField(max_length=50)),
            ],
        ),
    ]
